export { Home } from './Home';
export { ProductList } from './ProductList';
export { ProductDetail } from './ProductDetail';
export { Contact } from './Contact/Contact';
export { ContactIr } from './Contact/ContactIr';
export { ContactEu } from './Contact/ContactEu';
export { ContactUs } from './Contact/ContactUs';
export { Admin } from './Admin';
export { PageNotFound } from './PageNotFound';
